WIP: use API instead of in memory database
SeattleDSA/1-312-hows-my-driving pull request #27
Opened 2020-12-24 03:45 UTC by barrytam20

Opening a work in progress PR addressing #23 

Uses [API](https://github.com/barrytam20/spd-lookup) instead of in memory database for officer search.

Slightly changed search rules:
1. if badge is provided, do strict badge look up
2. instead of supporting wildcard search for names, does fuzzy search for name
    - if both first and last name are provided, fuzzy search for full name
    - else, fuzzy search for whatever is provided

I realize this is a pretty big change, so opening this as more of a request for comment than anything else. Also, I realize that this creates a dependency on my project. I am more than happy to transfer ownership of that project to this group

2021-01-11 06:07 UTC, AetherUnbound requested changes
Suggested change for the new API URL - also I think we can remove the ping code since we no longer have to worry about cold starts!

2021-01-11 06:07 UTC, AetherUnbound commented on src/dataset.py
> +DATA_API_HOST = "https://spd-lookup.herokuapp.com"
Now that we have the API accessible on the new server, this can be changed!
```suggestion
DATA_API_HOST = "https://1312api.tech-bloc-sea.dev"
```

2021-01-12 18:18 UTC, AetherUnbound approved these changes
Looks great! I'll merge it in as soon as I get an opportunity to test it locally 😄

2021-01-16 04:41 UTC, AetherUnbound commented
Okay testing this a bit more, and I'm getting some odd results from the API: https://1312api.tech-bloc-sea.dev/officer/search?first_name=&last_name=Morris
Why would this query return `Morrow` and `Norris`?

2021-01-16 04:46 UTC, AetherUnbound commented
> Okay testing this a bit more, and I'm getting some odd results from the API: https://1312api.tech-bloc-sea.dev/officer/search?first_name=&last_name=Morris
> Why would this query return `Morrow` and `Norris`?

Ahh, okay, this has to do with your recent [fuzzy search](https://github.com/barrytam20/spd-lookup/commit/5d337f8167ca280b0342f80e763da55d83088126) implementation! This is sort of unrelated to the PR, but is it possible to only do a fuzzy search if a certain character is added? For instance, `Morris` would only search "Morris" but `Morris?` would fuzzy search for "Morris"? Do you think that would make sense?

Regardless, this PR

2021-01-16 16:13 UTC, barrytam20 commented
Yea right now, named searches default to fuzzy search. There is an api endpoint for exact match; we might want to think of the UX in terms of when to invoke fuzzy search vs exact match (maybe a checkbox instead of a `?`)

2021-01-16 17:09 UTC, mpuckett159 commented
Yeah I like the checkbox idea, since the API makes it easy to just switch between the two, and it gives users an easy to understand visual cue. Reduces how busy the window will be. Should probably default to fuzzy search.

2021-01-17 00:52 UTC, AetherUnbound commented
Got it! Yes, agreed with you both - I'll make a separate ticket for the fuzzy searching option.

2021-01-20 03:01 UTC, merged